[2024-05-09T08:48:58.363+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T08:48:58.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag4.scraping_data manual__2024-05-09T08:48:53.272406+00:00 [queued]>
[2024-05-09T08:48:58.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag4.scraping_data manual__2024-05-09T08:48:53.272406+00:00 [queued]>
[2024-05-09T08:48:58.400+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T08:48:58.420+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scraping_data> on 2024-05-09 08:48:53.272406+00:00
[2024-05-09T08:48:58.450+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag4', 'scraping_data', 'manual__2024-05-09T08:48:53.272406+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpy95mv_ow']
[2024-05-09T08:48:58.454+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask scraping_data
[2024-05-09T08:48:58.456+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T08:48:58.457+0000] {standard_task_runner.py:63} INFO - Started process 231 to run task
[2024-05-09T08:48:58.613+0000] {task_command.py:426} INFO - Running <TaskInstance: welcome_dag4.scraping_data manual__2024-05-09T08:48:53.272406+00:00 [running]> on host eb2a699741de
[2024-05-09T08:48:58.774+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag4' AIRFLOW_CTX_TASK_ID='scraping_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T08:48:53.272406+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T08:48:53.272406+00:00'
[2024-05-09T08:48:58.779+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T08:48:58.806+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T08:48:58.807+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dag.py", line 34, in scraping
    paper_info_path , ref_info_path = get_scraping()
                                      ^^^^^^^^^^^^
NameError: name 'get_scraping' is not defined
[2024-05-09T08:48:58.829+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=welcome_dag4, task_id=scraping_data, run_id=manual__2024-05-09T08:48:53.272406+00:00, execution_date=20240509T084853, start_date=20240509T084858, end_date=20240509T084858
[2024-05-09T08:48:58.852+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task scraping_data (name 'get_scraping' is not defined; 231)
[2024-05-09T08:48:58.875+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T08:48:58.896+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T08:48:58.908+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
